---
- name: ensure dependencies are installed.
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ zabbix_server_const[ansible_os_family]['dependencies'] }}"

- name: add zabbix repo
  block:
    - name: add zabbix repository gpg key
      ansible.builtin.rpm_key:
        key: "{{ zabbix_server_const[ansible_os_family]['zabbix_gpg'] }}"
        state: present

    - name: add zabbix repository
      ansible.builtin.package:
        name: "{{ zabbix_server_const[ansible_os_family]['zabbix_repo'] }}"
        state: present
  when: zabbix_server.repo == "zabbix"

- name: install zabbix packages.
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ zabbix_server_const[ansible_os_family]['packages'] }}"