--- 
- name: merge dictionaries
  block:
  - name: register default vars
    include_vars: 
      file: ../../darexsu.zabbix_server/defaults/main.yml
      name: zabbix_server_default_vars
  
  - name: merge default and new dictionaries 
    set_fact:
      "{{ item.key }}": "{{ zabbix_server_default_vars[item.key] | combine(merge[item.key], recursive=True)}}"
    when: zabbix_server_default_vars[item.key] is defined
    with_dict: "{{ merge }}"

  - name: combine defaults vars with merge dictionary
    set_fact:
      merge: "{{ zabbix_server_default_vars | combine(merge, recursive=True)}}"
  when: merge is defined

- name: zabbix_server role is disabled
  meta: end_play
  when: not zabbix_server.enabled

- name: include zabbix_server install
  include_tasks: ./tasks/install/zabbix_server_install__{{ ansible_os_family | lower }}.yml
  when: zabbix_server_install.enabled

- name: include zabbix_server config
  include_tasks: ./tasks/config/zabbix_server_conf__{{ ansible_os_family | lower }}.yml
  when: zabbix_server_conf.enabled

- name: include mariadb tasks
  include_tasks: ./tasks/mariadb/zabbix_server_mariadb__{{ ansible_os_family | lower }}.yml
  when: mariadb.enabled

- name: include php tasks
  include_tasks: ./tasks/php/zabbix_server_php.yml
  when: php.enabled
    
- name: include nginx tasks
  include_tasks: ./tasks/nginx/zabbix_server_nginx.yml
  when: nginx.enabled

- name: zabbix-server service
  ansible.builtin.service:
    name: zabbix-server
    state: "{{ zabbix_server.service.state }}"
    enabled: "{{ zabbix_server.service.enabled }}"