---
- name: "Merge dictionaries"
  block:
    - name: "Register default vars"
      include_vars:
        file: ../../darexsu.zabbix_server/defaults/main.yml
        name: zabbix_server_default_vars

    - name: "Merge default and new dictionaries"
      set_fact:
        "{{ item.key }}": "{{ zabbix_server_default_vars[item.key] | combine(merge[item.key], recursive=True)}}"
      when: zabbix_server_default_vars[item.key] is defined
      with_dict: "{{ merge }}"

    - name: "Combine defaults vars with merge dictionary"
      set_fact:
        merge: "{{ zabbix_server_default_vars | combine(merge, recursive=True)}}"
  when: merge is defined

- name: "Zabbix_server role is disabled"
  meta: end_play
  when: not zabbix_server.enabled

- name: "Include role -> darexsu.mariadb"
  include_role:
    name: darexsu.mariadb
  when: mariadb.enabled

- name: "include role -> darexsu.mysql"
  include_role:
    name: darexsu.mysql
  when: mysql.enabled

- name: "-> 01_Zabbix_server_install_{{ ansible_os_family }}.yml"
  include_tasks: ./tasks/01_Zabbix_server_install_{{ ansible_os_family }}.yml
  when: zabbix_server_install.enabled

- name: "Service facts"
  ansible.builtin.service_facts:

- name: "-> 02_Zabbix_server_config.yml"
  include_tasks: ./tasks/02_Zabbix_server_config.yml
  when: ansible_facts.services is search("zabbix-server") and zabbix_server_conf.enabled

- name: "-> 03_MariaDB_tasks.yml"
  include_tasks: ./tasks/03_MariaDB_tasks.yml
  when: mariadb.enabled

- name: "-> 03_MySQL_tasks.yml"
  include_tasks: ./tasks/03_MySQL_tasks.yml
  when: mysql.enabled

- name: "include role -> darexsu.firewalld"
  include_role:
    name: darexsu.firewalld
  when: firewalld.enabled

- name: "Ensure Zabbix-server {{ zabbix_server.service.state }}"
  ansible.builtin.service:
    name: zabbix-server
    state: "{{ zabbix_server.service.state }}"
    enabled: "{{ zabbix_server.service.enabled }}"
  when: ansible_facts.services is search("zabbix-server")