---
- name: merge dictionaries
  block:
  - name: register default vars
    include_vars:
      file: ../../darexsu.zabbix_server/defaults/main.yml
      name: zabbix_server_default_vars

  - name: merge default and new dictionaries
    set_fact:
      "{{ item.key }}": "{{ zabbix_server_default_vars[item.key] | combine(merge[item.key], recursive=True)}}"
    when: zabbix_server_default_vars[item.key] is defined
    with_dict: "{{ merge }}"

  - name: combine defaults vars with merge dictionary
    set_fact:
      merge: "{{ zabbix_server_default_vars | combine(merge, recursive=True)}}"
  when: merge is defined

- name: zabbix_server role is disabled
  meta: end_play
  when: not zabbix_server.enabled

- name: include mariadb install_and_config
  include_tasks: ./tasks/mariadb/install_and_config.yml
  when: mariadb.enabled

- name: include mysql install_and_config
  include_tasks: ./tasks/mysql/install_and_config.yml
  when: mysql.enabled

- name: include zabbix_server install
  include_tasks: ./tasks/zabbix_server/install/zabbix_server__install_{{ ansible_os_family }}.yml
  when: zabbix_server_install.enabled

- name: include zabbix_server config
  include_tasks: ./tasks/zabbix_server/config/zabbix_server__conf.yml
  when: zabbix_server_conf.enabled

- name: include mariadb tasks
  include_tasks: ./tasks/mariadb/tasks.yml
  when: mariadb.enabled

- name: include mysql tasks
  include_tasks: ./tasks/mysql/tasks.yml
  when: mysql.enabled

- name: zabbix-server service
  ansible.builtin.service:
    name: zabbix-server
    state: "{{ zabbix_server.service.state }}"
    enabled: "{{ zabbix_server.service.enabled }}"