---
- name: configure zabbix_server.conf
  ansible.builtin.template:
    src: "{{ zabbix_server_conf.src }}"
    dest: "{{ zabbix_server_conf.path.redhat }}{{ zabbix_server_conf.file }}"
    owner: root
    group: root
    mode: 0600
    backup: "{{ zabbix_server_conf.backup }}"
  notify: restart zabbix-server
  when: zabbix_server_conf.enabled