---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
  - name: Unnessessary command
    ansible.builtin.shell:
      cmd: "{{ lookup('env', 'ANSIBLE_COMMAND') }}"
    when: lookup('env', 'ANSIBLE_COMMAND') | length > 0

  vars:
    merge:
      # Zabbix_server
      zabbix_server:
        enabled: true
        src: "third_party"
        version: "6.0"
        server_name: "Zabbix server"
        db_type: "MYSQL"
        db_port: "3306"
        db_host: "localhost"
        db_name: "zabbix"
        db_user: "zabbix"
        db_password: "change_me"
        service:
          state: "started"
          enabled: true

      # Zabbix_server -> install
      zabbix_server_install:
        enabled: true
        packages:
          Debian: [zabbix-server-mysql, zabbix-agent, zabbix-sql-scripts]
          RedHat: [zabbix-server-mysql, zabbix-agent, zabbix-sql-scripts]
        dependencies:
          Debian: [apt-transport-https, ca-certificates, gnupg2, lsb-release]
          RedHat: []

      # Zabbix_server -> config
      zabbix_server_conf:
        enabled: true
        file: "zabbix_server.conf"
        src: "zabbix_server_conf.j2"
        backup: false
        vars:
          ListenPort: "10051"
          LogFile: "/var/log/zabbix/zabbix_server.log"
          LogFileSize: "0"
          PidFile: "/var/run/zabbix/zabbix_server.pid"
          SocketDir: "/var/run/zabbix"
          DBHost: "{{ zabbix_server.db_host }}"
          DBName: "{{ zabbix_server.db_name }}"
          DBSchema: ""
          DBUser: "{{ zabbix_server.db_user }}"
          DBPassword: "{{ zabbix_server.db_password }}"
          DBSocket: ""
          DBPort: "{{ zabbix_server.db_port }}"
          SNMPTrapperFile: "/var/log/snmptrap/snmptrap.log"
          CacheUpdateFrequency: "60"
          Timeout: "4"
          AlertScriptsPath: "/usr/lib/zabbix/alertscripts"
          ExternalScripts: "/usr/lib/zabbix/externalscripts"
          FpingLocation: "/usr/bin/fping"
          Fping6Location: "/usr/bin/fping6"
          LogSlowQueries: "3000"

      # MariaDB
      mariadb:
        enabled: true
        src: "third_party"
        version: "10.5"

      # MariaDB -> install
      mariadb_install:
        enabled: true

      # MariaDB -> database
      mariadb_database:
        zabbix_server:
          enabled: true
          remove_old: true
          login_user: "root"
          login_password: ""
          login_host: "localhost"
          login_port: "{{ zabbix_server.db_port }}"
          login_unix_socket: "{{ mariadb_const[ansible_os_family]['socket'] }}"
          name: "{{ zabbix_server.db_name }}"
          state: "present"
          target: ""
          encoding: "utf8"
          collation: "utf8_bin"

      # MariaDB -> user
      mariadb_user:
        zabbix_server:
          enabled: true
          login_user: "root"
          login_password: ""
          login_host: "localhost"
          login_port: "{{ zabbix_server.db_port }}"
          login_unix_socket: "{{ mariadb_const[ansible_os_family]['socket'] }}"
          name: "{{ zabbix_server.db_user }}"
          password: "{{ zabbix_server.db_password }}"
          state: "present"
          privileges: 'zabbix.*:ALL'
          encrypted: false

      # MariaDB -> sql
      mariadb_sql:
        zabbix_server:
          schema: true

      # FirewallD
      firewalld:
        enabled: true
      # FirewallD -> rules
      firewalld_rules:
        zabbix_port_10050:
          enabled: true
          zone: "public"
          state: "enabled"
          port: "10050/tcp"
          permanent: true
        zabbix_port_10051:
          enabled: true
          zone: "public"
          state: "enabled"
          port: "10051/tcp"
          permanent: true
        mysql_port_3306:
          enabled: true
          zone: "public"
          state: "enabled"
          port: "3306/tcp"
          permanent: true

  tasks:
    - name: include role darexsu.zabbix_server
      include_role:
        name: darexsu.zabbix_server